version: "3"

services:
  express-app:
    build:
      context: ./express-product-app
    ports:
      - "3000:3000" #host:container

  react-app:
    build:
      context: ./react-product-app
    ports:
      - "3001:3000" #host:container
    environment:
      - REACT_APP_API_ENDPOINT=http://192.168.29.206:3000/products
